require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/internal/bin/*'
    - 'spec/internal/db/schema.rb'

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/hydra/works/characterization/fits_document.rb

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribedClass:
  Exclude:
    - spec/hydra/works/models/concerns/generic_file/characterization_spec.rb

RSpec/AnyInstance:
  Exclude:
    - spec/hydra/works/services/persist_derivatives_spec.rb
